//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAppRest.WsAusa {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ausades01//SVU//", ConfigurationName="WsAusa.WS_SVUSoap")]
    public interface WS_SVUSoap {
        
        // CODEGEN: Generating message contract since element name userName from namespace http://ausades01//SVU// is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ausades01//SVU//nuevaAutenticacion", ReplyAction="*")]
        MvcAppRest.WsAusa.nuevaAutenticacionResponse nuevaAutenticacion(MvcAppRest.WsAusa.nuevaAutenticacionRequest request);
        
        // CODEGEN: Generating message contract since element name devolverCateraClientesResult from namespace http://ausades01//SVU// is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ausades01//SVU//devolverCateraClientes", ReplyAction="*")]
        MvcAppRest.WsAusa.devolverCateraClientesResponse devolverCateraClientes(MvcAppRest.WsAusa.devolverCateraClientesRequest request);
        
        // CODEGEN: Generating message contract since element name devolverRolesResult from namespace http://ausades01//SVU// is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ausades01//SVU//devolverRoles", ReplyAction="*")]
        MvcAppRest.WsAusa.devolverRolesResponse devolverRoles(MvcAppRest.WsAusa.devolverRolesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nuevaAutenticacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="nuevaAutenticacion", Namespace="http://ausades01//SVU//", Order=0)]
        public MvcAppRest.WsAusa.nuevaAutenticacionRequestBody Body;
        
        public nuevaAutenticacionRequest() {
        }
        
        public nuevaAutenticacionRequest(MvcAppRest.WsAusa.nuevaAutenticacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ausades01//SVU//")]
    public partial class nuevaAutenticacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public nuevaAutenticacionRequestBody() {
        }
        
        public nuevaAutenticacionRequestBody(string userName, string password) {
            this.userName = userName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nuevaAutenticacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="nuevaAutenticacionResponse", Namespace="http://ausades01//SVU//", Order=0)]
        public MvcAppRest.WsAusa.nuevaAutenticacionResponseBody Body;
        
        public nuevaAutenticacionResponse() {
        }
        
        public nuevaAutenticacionResponse(MvcAppRest.WsAusa.nuevaAutenticacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ausades01//SVU//")]
    public partial class nuevaAutenticacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nuevaAutenticacionResult;
        
        public nuevaAutenticacionResponseBody() {
        }
        
        public nuevaAutenticacionResponseBody(string nuevaAutenticacionResult) {
            this.nuevaAutenticacionResult = nuevaAutenticacionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class devolverCateraClientesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="devolverCateraClientes", Namespace="http://ausades01//SVU//", Order=0)]
        public MvcAppRest.WsAusa.devolverCateraClientesRequestBody Body;
        
        public devolverCateraClientesRequest() {
        }
        
        public devolverCateraClientesRequest(MvcAppRest.WsAusa.devolverCateraClientesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ausades01//SVU//")]
    public partial class devolverCateraClientesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int usuario;
        
        public devolverCateraClientesRequestBody() {
        }
        
        public devolverCateraClientesRequestBody(int usuario) {
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class devolverCateraClientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="devolverCateraClientesResponse", Namespace="http://ausades01//SVU//", Order=0)]
        public MvcAppRest.WsAusa.devolverCateraClientesResponseBody Body;
        
        public devolverCateraClientesResponse() {
        }
        
        public devolverCateraClientesResponse(MvcAppRest.WsAusa.devolverCateraClientesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ausades01//SVU//")]
    public partial class devolverCateraClientesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string devolverCateraClientesResult;
        
        public devolverCateraClientesResponseBody() {
        }
        
        public devolverCateraClientesResponseBody(string devolverCateraClientesResult) {
            this.devolverCateraClientesResult = devolverCateraClientesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class devolverRolesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="devolverRoles", Namespace="http://ausades01//SVU//", Order=0)]
        public MvcAppRest.WsAusa.devolverRolesRequestBody Body;
        
        public devolverRolesRequest() {
        }
        
        public devolverRolesRequest(MvcAppRest.WsAusa.devolverRolesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ausades01//SVU//")]
    public partial class devolverRolesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int usr;
        
        public devolverRolesRequestBody() {
        }
        
        public devolverRolesRequestBody(int usr) {
            this.usr = usr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class devolverRolesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="devolverRolesResponse", Namespace="http://ausades01//SVU//", Order=0)]
        public MvcAppRest.WsAusa.devolverRolesResponseBody Body;
        
        public devolverRolesResponse() {
        }
        
        public devolverRolesResponse(MvcAppRest.WsAusa.devolverRolesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ausades01//SVU//")]
    public partial class devolverRolesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string devolverRolesResult;
        
        public devolverRolesResponseBody() {
        }
        
        public devolverRolesResponseBody(string devolverRolesResult) {
            this.devolverRolesResult = devolverRolesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_SVUSoapChannel : MvcAppRest.WsAusa.WS_SVUSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_SVUSoapClient : System.ServiceModel.ClientBase<MvcAppRest.WsAusa.WS_SVUSoap>, MvcAppRest.WsAusa.WS_SVUSoap {
        
        public WS_SVUSoapClient() {
        }
        
        public WS_SVUSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_SVUSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_SVUSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_SVUSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MvcAppRest.WsAusa.nuevaAutenticacionResponse MvcAppRest.WsAusa.WS_SVUSoap.nuevaAutenticacion(MvcAppRest.WsAusa.nuevaAutenticacionRequest request) {
            return base.Channel.nuevaAutenticacion(request);
        }
        
        public string nuevaAutenticacion(string userName, string password) {
            MvcAppRest.WsAusa.nuevaAutenticacionRequest inValue = new MvcAppRest.WsAusa.nuevaAutenticacionRequest();
            inValue.Body = new MvcAppRest.WsAusa.nuevaAutenticacionRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            MvcAppRest.WsAusa.nuevaAutenticacionResponse retVal = ((MvcAppRest.WsAusa.WS_SVUSoap)(this)).nuevaAutenticacion(inValue);
            return retVal.Body.nuevaAutenticacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MvcAppRest.WsAusa.devolverCateraClientesResponse MvcAppRest.WsAusa.WS_SVUSoap.devolverCateraClientes(MvcAppRest.WsAusa.devolverCateraClientesRequest request) {
            return base.Channel.devolverCateraClientes(request);
        }
        
        public string devolverCateraClientes(int usuario) {
            MvcAppRest.WsAusa.devolverCateraClientesRequest inValue = new MvcAppRest.WsAusa.devolverCateraClientesRequest();
            inValue.Body = new MvcAppRest.WsAusa.devolverCateraClientesRequestBody();
            inValue.Body.usuario = usuario;
            MvcAppRest.WsAusa.devolverCateraClientesResponse retVal = ((MvcAppRest.WsAusa.WS_SVUSoap)(this)).devolverCateraClientes(inValue);
            return retVal.Body.devolverCateraClientesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MvcAppRest.WsAusa.devolverRolesResponse MvcAppRest.WsAusa.WS_SVUSoap.devolverRoles(MvcAppRest.WsAusa.devolverRolesRequest request) {
            return base.Channel.devolverRoles(request);
        }
        
        public string devolverRoles(int usr) {
            MvcAppRest.WsAusa.devolverRolesRequest inValue = new MvcAppRest.WsAusa.devolverRolesRequest();
            inValue.Body = new MvcAppRest.WsAusa.devolverRolesRequestBody();
            inValue.Body.usr = usr;
            MvcAppRest.WsAusa.devolverRolesResponse retVal = ((MvcAppRest.WsAusa.WS_SVUSoap)(this)).devolverRoles(inValue);
            return retVal.Body.devolverRolesResult;
        }
    }
}
